### ISSUE TITLE
Cannot find '/vagrant/nomad-server.hcl' during provisioning

### ISSUE THREAD

**Issue by mrlesmithjr** [discoposse/nomad-3-node-lab#1]
When doing a `vagrant up` and the shell script provisioning kicks in we are presented with the following error (for each host):

```bash
nomad-a-1: cp:
nomad-a-1: cannot stat '/vagrant/nomad-server.hcl'
nomad-a-1: : No such file or directory
```

The script is failing at [line#35](https://github.com/discoposse/nomad-vagrant-lab/blob/master/node-install.sh#L35)

**Comment by discoposse** [comment]
Just pushed an update. I forgot I was working a commit ahead on my local machine. Thanks for catching this!
