### ISSUE TITLE
README and Blog Post should be in sync? ;)

### ISSUE THREAD

**Issue by mrlesmithjr** [discoposse/nomad-3-node-lab#2]
So, following the [blog post](https://discoposse.com/2019/11/21/building-a-hashicorp-nomad-cluster-lab-using-vagrant-and-virtualbox/) the following instructions seem incorrect:

Connect via ssh to the first node using the command vagrant ssh nomad-a-1
Change to the code folder with the command cd /vagrant
Launch the Nomad script with this command:  **sudo sh launch nomad-a-1.sh**
Connect via ssh to the second node using the command vagrant ssh nomad-a-2
Change to the code folder with the command cd /vagrant
Launch the Nomad script with this command:  **sudo sh launch nomad-a-2.sh**
Connect via ssh to the third node using the command vagrant ssh nomad-a-3
Change to the code folder with the command cd /vagrant
Launch the Nomad script with this command:  **sudo sh launch nomad-a-3.sh**

I believe they should be:

Connect via ssh to the first node using the command vagrant ssh nomad-a-1
Change to the code folder with the command cd /vagrant
Launch the Nomad script with this command:  **sudo sh launch-a-1.sh**
Connect via ssh to the second node using the command vagrant ssh nomad-a-2
Change to the code folder with the command cd /vagrant
Launch the Nomad script with this command:  **sudo sh launch-a-2.sh**
Connect via ssh to the third node using the command vagrant ssh nomad-a-3
Change to the code folder with the command cd /vagrant
Launch the Nomad script with this command:  **sudo sh launch-a-3.sh**

**Comment by discoposse** [comment]
Fixed, thank you! Bad copy/paste on my part.
