### ISSUE TITLE
Nomad Cluster Does Not Form Because Of Consul Cluster Not Available

### ISSUE THREAD

**Issue by mrlesmithjr** [discoposse/nomad-3-node-lab#3]
When attempting to spin up Nomad cluster it fails because the backend Consul cluster is not up and running. We need to tweak the spin up script(s) to form the Consul cluster first before forming the Nomad cluster.

**Comment by discoposse** [comment]
Thank you Larry! I did leave this off the first iteration because Nomad works without Consul. It's ideal to have everything working together though.
