### ISSUE TITLE
Direction of scripts for spinning up Consul/Nomad clusters

### ISSUE THREAD

**Issue by mrlesmithjr** [discoposse/nomad-3-node-lab#7]
@discoposse What are your thoughts on the direction of the scripts to spin up Consul/Nomad clusters?

Now that I know this repo is for usage of the Pluralsight course as well, is your idea that the user is to login to each node and spin up these services? Which would lead them into further learning potentially? Or does it make sense to have these services up, running and ready for interaction?

**Comment by mrlesmithjr** [comment]
I also believe that I may have jumped the gun on spinning up Consul as part of the PR's I have submitted. In your documentation you mention that there will be more to come with Consul. So, I want to ensure that any PR's I submit are in line with your flow of blog posts, Pluralsight course(s), etc.

Just glad to help out where I can but keep me in check on where you are with content. If I need to pull some things back, just let me know..

Keep up the great work!

**Comment by discoposse** [comment]
All good! We can roll with it as is and I'll build some content to adjust to the auto-start :)
